//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOO_Восток.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        public int IDRequest { get; set; }
        public int Product { get; set; }
        public int Client { get; set; }
        public int Manager { get; set; }
        public System.DateTime Data { get; set; }
        public int Status { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual StatusOfRequests StatusOfRequests { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
